export const SE_LOGER = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "In luctus diam varius odio aliquet, id pretium leo luctus.",
  "Nunc ac enim mollis, condimentum orci non, bibendum metus.",
  "Etiam ornare massa sed nisi volutpat, in ultrices leo tristique.",
  "Nam non elit aliquet sapien pellentesque imperdiet.",
  "Curabitur porttitor dolor a leo dictum dictum.",
  "Nullam sed arcu ultricies leo rhoncus mattis et ut massa.",
  "Ut efficitur turpis eget enim suscipit iaculis.",
  "Aenean id mi eleifend, fringilla est et, pharetra enim.",
  "Nunc suscipit justo vitae elit commodo blandit.",
  "Nullam aliquam ipsum eu lacinia tristique.",
  "Quisque scelerisque mi ut nunc rutrum tristique.",
  "Donec volutpat nisl quis urna gravida porta.",
  "Curabitur fermentum sem nec enim consectetur iaculis.",
]

export const SE_NOURRIR = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "In luctus diam varius odio aliquet, id pretium leo luctus.",
  "Nunc ac enim mollis, condimentum orci non, bibendum metus.",
  "Etiam ornare massa sed nisi volutpat, in ultrices leo tristique.",
  "Nam non elit aliquet sapien pellentesque imperdiet.",
  "Curabitur porttitor dolor a leo dictum dictum.",
  "Nullam sed arcu ultricies leo rhoncus mattis et ut massa.",
  "Ut efficitur turpis eget enim suscipit iaculis.",
  "Aenean id mi eleifend, fringilla est et, pharetra enim.",
  "Nunc suscipit justo vitae elit commodo blandit.",
  "Nullam aliquam ipsum eu lacinia tristique.",
  "Quisque scelerisque mi ut nunc rutrum tristique.",
  "Donec volutpat nisl quis urna gravida porta.",
  "Curabitur fermentum sem nec enim consectetur iaculis.",
]

export const SE_DEPLACER = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "In luctus diam varius odio aliquet, id pretium leo luctus.",
  "Nunc ac enim mollis, condimentum orci non, bibendum metus.",
  "Etiam ornare massa sed nisi volutpat, in ultrices leo tristique.",
  "Nam non elit aliquet sapien pellentesque imperdiet.",
  "Curabitur porttitor dolor a leo dictum dictum.",
  "Nullam sed arcu ultricies leo rhoncus mattis et ut massa.",
  "Ut efficitur turpis eget enim suscipit iaculis.",
  "Aenean id mi eleifend, fringilla est et, pharetra enim.",
  "Nunc suscipit justo vitae elit commodo blandit.",
  "Nullam aliquam ipsum eu lacinia tristique.",
  "Quisque scelerisque mi ut nunc rutrum tristique.",
  "Donec volutpat nisl quis urna gravida porta.",
  "Curabitur fermentum sem nec enim consectetur iaculis.",
]

export const CONSOMMER = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "In luctus diam varius odio aliquet, id pretium leo luctus.",
  "Nunc ac enim mollis, condimentum orci non, bibendum metus.",
  "Etiam ornare massa sed nisi volutpat, in ultrices leo tristique.",
  "Nam non elit aliquet sapien pellentesque imperdiet.",
  "Curabitur porttitor dolor a leo dictum dictum.",
  "Nullam sed arcu ultricies leo rhoncus mattis et ut massa.",
  "Ut efficitur turpis eget enim suscipit iaculis.",
  "Aenean id mi eleifend, fringilla est et, pharetra enim.",
  "Nunc suscipit justo vitae elit commodo blandit.",
  "Nullam aliquam ipsum eu lacinia tristique.",
  "Quisque scelerisque mi ut nunc rutrum tristique.",
  "Donec volutpat nisl quis urna gravida porta.",
  "Curabitur fermentum sem nec enim consectetur iaculis.",
]

export const PRODUIRE = [
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
  "In luctus diam varius odio aliquet, id pretium leo luctus.",
  "Nunc ac enim mollis, condimentum orci non, bibendum metus.",
  "Etiam ornare massa sed nisi volutpat, in ultrices leo tristique.",
  "Nam non elit aliquet sapien pellentesque imperdiet.",
  "Curabitur porttitor dolor a leo dictum dictum.",
  "Nullam sed arcu ultricies leo rhoncus mattis et ut massa.",
  "Ut efficitur turpis eget enim suscipit iaculis.",
  "Aenean id mi eleifend, fringilla est et, pharetra enim.",
  "Nunc suscipit justo vitae elit commodo blandit.",
  "Nullam aliquam ipsum eu lacinia tristique.",
  "Quisque scelerisque mi ut nunc rutrum tristique.",
  "Donec volutpat nisl quis urna gravida porta.",
  "Curabitur fermentum sem nec enim consectetur iaculis.",
]
